export default {
    /** The "usernames" of each chat actor (sender or receiver) to show in chats */
    actors: {
        /** The user username */
        USER: "You",
        /** The AI username */
        AI: "DataSage",
    },
    /** The message to be shown when the AI is generating a response */
    WRITING_RESPONSE: "DataSage is writing...",
    /** The chat message conversation input related variables */
    input: {
        /** Label of the input field */
        LABEL: "Chat Message Input",
        /** Placeholder of the input field */
        PLACEHOLDER: "Message to be sent to chat...",
    },
    /** Contains all messages related to the sources section of the chat messages (For those generated by AI). */
    sources: {
        /** Message that introduces the sources section (context used) of an AI generated message. */
        INTRODUCTION: "Sources:",
        /** Function that builds a single source text from a location page. (Should be used inside a link to the source). */
        buildSourceMessage: (locationPage) => `Page ${locationPage}`,
    },
};
